services:
  fastapi_app:
    build: 
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      elixir_app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3

  elixir_app:
    build: 
      context: ./elixir_app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: vacation_network
    driver: bridge