services:
  elixir_app:
    build:
      context: ./elixir_app  # ¡Punto clave!
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./elixir_app:/app
    environment:
      - MIX_ENV=prod
    working_dir: /app

  fastapi_app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    depends_on:
      - elixir_app
    working_dir: /app